### ISSUE TITLE
처음부터 다시 작업하고 계신가요?

### ISSUE THREAD

**Issue by KiwiFlavoredApollo** [sebuls/phpBB3ko#1]
안녕하세요. phpBB 포럼에서 글 보고 연락드립니다. 혹시 처음부터 다시 번역하고 계신가요? 혹시 참고하고 계신 자료가 있다면 그것을 기반으로 pull request를 보내려고 합니다.

**Comment by sebuls** [comment]
이것 저것 참고하고 있습니다. American English 도 보고, 일본어 번역도 보고, 다른 분이 작업하다가 만 한국어 번역도 보고. 그런데, 제가 영어도 잘 못하고, git 에도 익숙하지 않아서 좌충우돌하고 있네요. 님께서 pull request 보내준다면 제가 그걸 어떻게 해야 되는지도 몰라요. ;)

**Comment by KiwiFlavoredApollo** [comment]
아하.. 알겠습니다. 감사합니다.

**Comment by sebuls** [comment]
저도 파파고 등 번역기를 활용하고 어색한 번역을 손보면서 진행하고 있습니다.
